import { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import { useState } from "react"
import Navbar from "../src/components/Navbar"
import Footer from "../src/components/Footer"
import Hero from "../src/components/Sections/Home/Hero"
import Sidebar from "../src/components/Sidebar"
import Features from "../src/components/Sections/Home/Features"
import { PricesPoS } from "../src/components/Sections/Home/PricesPoS"
import Terms from "../src/components/Sections/Terms"

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);

  const toggle = () => {
    setIsOpen((prev) => !prev);
  };

  return (
    <>
      <Head>
        <title>Kubbent - Bitcoiner Company</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Terms/>
      {/* <Footer/> */}
    </>
  )
}